"""
update_data.py
--------------
Baca Datamart_Risiko_Operasional.xlsx (sheet DATAMART + LAPORAN)
→ generate public/data.js untuk portal web.

Jalankan setiap kali selesai update Excel, lalu git push ke GitHub.
Vercel otomatis re-deploy dalam ~30 detik.

Usage:
    python update_data.py
"""

import json, sys, re
from pathlib import Path
from datetime import datetime
from openpyxl import load_workbook

BASE       = Path(__file__).parent
EXCEL_FILE = BASE / "Datamart_Risiko_Operasional.xlsx"
OUT_FILE   = BASE / "public" / "data.js"


def read_datamart(wb):
    ws = wb["DATAMART"]
    row3 = [ws.cell(row=3, column=c).value for c in range(1, ws.max_column + 1)]
    periods, period_cols = [], {}
    for ci, val in enumerate(row3):
        s = str(val).strip() if val is not None else ""
        if re.match(r"^\d{6}$", s):
            periods.append(s)
            period_cols[s] = ci + 1
    if not periods:
        print("ERROR: Tidak ada kolom periode di sheet DATAMART.")
        sys.exit(1)
    periods.sort()
    rows = []
    for er in range(5, ws.max_row + 1):
        par = ws.cell(row=er, column=3).value
        if not par or str(par).strip() == "":
            continue
        row = {
            "key": str(ws.cell(row=er, column=1).value or "").strip(),
            "bag": str(ws.cell(row=er, column=2).value or "").strip(),
            "par": str(par).strip(),
            "jen": str(ws.cell(row=er, column=4).value or "").strip(),
            "lnk": str(ws.cell(row=er, column=5).value or "").strip(),
        }
        for p in periods:
            val = ws.cell(row=er, column=period_cols[p]).value
            row[p] = None if (val is None or str(val).strip() == "") else str(val).strip()
        rows.append(row)
    print(f"  DATAMART : {len(rows)} parameter, {len(periods)} periode")
    return {"periods": periods, "rows": rows}


def read_laporan(wb):
    if "LAPORAN" not in wb.sheetnames:
        print("  LAPORAN  : sheet tidak ditemukan, dilewati.")
        return []
    ws = wb["LAPORAN"]
    files = []
    for er in range(5, ws.max_row + 1):
        nama = ws.cell(row=er, column=1).value
        if not nama or str(nama).strip() == "":
            continue
        aktif = str(ws.cell(row=er, column=8).value or "Y").strip().upper()
        if aktif != "Y":
            continue
        files.append({
            "nama":  str(nama).strip(),
            "desc":  str(ws.cell(row=er, column=2).value or "").strip(),
            "kat":   str(ws.cell(row=er, column=3).value or "Dokumen").strip(),
            "tipe":  str(ws.cell(row=er, column=4).value or "pdf").strip().lower(),
            "link":  str(ws.cell(row=er, column=5).value or "").strip(),
            "ukuran":str(ws.cell(row=er, column=6).value or "").strip(),
            "tgl":   str(ws.cell(row=er, column=7).value or "").strip(),
        })
    print(f"  LAPORAN  : {len(files)} dokumen aktif")
    return files


def main():
    if not EXCEL_FILE.exists():
        print(f"ERROR: File tidak ditemukan → {EXCEL_FILE}")
        sys.exit(1)
    print(f"Membaca {EXCEL_FILE.name}...")
    wb = load_workbook(EXCEL_FILE, data_only=True)
    dm      = read_datamart(wb)
    laporan = read_laporan(wb)
    ts      = datetime.now().strftime("%Y-%m-%d %H:%M")
    payload = {
        "periods": dm["periods"],
        "rows":    dm["rows"],
        "laporan": laporan,
        "updated": ts,
    }
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    js = (
        f"// Auto-generated by update_data.py — {ts}\n"
        f"// Jangan edit manual. Edit Excel lalu jalankan script ini.\n"
        f"window.DATAMART = {json.dumps(payload, ensure_ascii=False, indent=2)};\n"
    )
    OUT_FILE.write_text(js, encoding="utf-8")
    print(f"\n✓ Berhasil → {OUT_FILE}")
    print(f"  {len(dm['rows'])} parameter · {len(dm['periods'])} periode · {len(laporan)} dokumen")
    print(f"\nSelanjutnya:")
    print(f"  git add public/data.js Datamart_Risiko_Operasional.xlsx")
    print(f"  git commit -m 'update data {dm['periods'][-1]}'")
    print(f"  git push")


if __name__ == "__main__":
    main()
